language: crystal
env: LLVM_VERSION=4.0
before_install:
  - nvm install node
before_script: |
  set -e
  CRYSTAL_INSTALL_DIR="$(crystal env CRYSTAL_PATH |  awk -F: '{print $1}')/../"
  echo $CRYSTAL_INSTALL_DIR
  sudo crystal env CRYSTAL_VERSION > "$CRYSTAL_INSTALL_DIR/VERSION"
  chown $USER "$CRYSTAL_INSTALL_DIR/VERSION"
