version: 2
jobs: # a collection of jobs
  build: 
    working_directory: ~/CrystalScript
    docker: # run build steps with docker
      - image: crystallang/crystal:0.27.0 # primary docker container; all `steps` will run here.
    steps:
      - checkout
      - run: apt-get update
      - run:
          name: install LLVM
          command: apt-get install llvm-4.0 llvm-4.0-dev --yes
      - run:
          name: install NodeJS
          command: |
            apt-get install curl --yes
            curl -sL https://deb.nodesource.com/setup_11.x | bash -
            apt-get install nodejs --yes
      - run: ./create_VERSION.sh
      - run:
          name: Install dependencies.
          command: shards install
      - run:
          name: Run tests
          command: crystal spec